name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
      - name: Install dependencies
        run: poetry install
      - name: Run linter
        run: poetry run flake8 fmla
      - name: Check format
        run: poetry run black --check fmla
      - name: Check imports
        run: poetry run isort --check fmla
      - name: Run type check
        run: poetry run mypy fmla
      - name: Run tests
        run: poetry run pytest
